// Generated by dts-bundle v0.7.3

declare module '@utkusarioglu/namespace' {
    export { M_Namespace } from "@utkusarioglu/namespace/m_namespace";
    export { t_namespace } from "@utkusarioglu/namespace/t_namespace";
}

declare module '@utkusarioglu/namespace/m_namespace' {
    import { t_namespace } from "@utkusarioglu/namespace/t_namespace";
    export abstract class M_Namespace {
        get_GlobalNamespace(): t_namespace;
        get_GlobalNamespaceStack(): t_namespace[];
        protected set_GlobalNamespace(global_namespace: t_namespace): this;
        get_LocalNamespace(): t_namespace;
        get_LocalNamespaceStack(): t_namespace[];
        protected set_LocalNamespace(local_namespace: t_namespace): void;
        has_LocalNamespace(): boolean;
    }
}

declare module '@utkusarioglu/namespace/t_namespace' {
    export type t_namespace = string;
    export type t_namespaceGenericObject = {
        [key: string]: any;
    };
}

